// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KayanHRAttendanceService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext.ApplicationDbContext))]
    [Migration("20250530231504_AddingAttendanceDataTable")]
    partial class AddingAttendanceDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KayanHRAttendanceService.Entities.Sqlite.AttendanceRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Function")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineSerialNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PunchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TId")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AttendanceData");
                });
#pragma warning restore 612, 618
        }
    }
}
