// <auto-generated />
using KayanHRAttendanceService.Infrastructure.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KayanHRAttendanceService.Infrastructure.ApplicationDbContext.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601095935_SeedDataToAttendanceRecord")]
    partial class SeedDataToAttendanceRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KayanHRAttendanceService.Domain.Entities.Sqlite.AttendanceRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineSerialNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PunchTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AttendanceData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EmployeeCode = "EMP001",
                            Function = "IN",
                            MachineName = "MainGate",
                            MachineSerialNo = "SN001",
                            PunchTime = "2025-06-01 08:00:00",
                            Status = "Verified",
                            TId = "T1001"
                        },
                        new
                        {
                            ID = 2,
                            EmployeeCode = "EMP002",
                            Function = "IN",
                            MachineName = "SideGate",
                            MachineSerialNo = "SN002",
                            PunchTime = "2025-06-01 08:15:00",
                            Status = "Verified",
                            TId = "T1002"
                        },
                        new
                        {
                            ID = 3,
                            EmployeeCode = "EMP001",
                            Function = "OUT",
                            MachineName = "MainGate",
                            MachineSerialNo = "SN001",
                            PunchTime = "2025-06-01 17:00:00",
                            Status = "Verified",
                            TId = "T1003"
                        },
                        new
                        {
                            ID = 4,
                            EmployeeCode = "EMP002",
                            Function = "OUT",
                            MachineName = "SideGate",
                            MachineSerialNo = "SN002",
                            PunchTime = "2025-06-01 17:05:00",
                            Status = "Verified",
                            TId = "T1004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
